#!/usr/bin/env sh

rofi_command="rofi -theme theme/powermenu.rasi"

### Options ###
power_off="Shutdown"
reboot="Reboot"
lock="Lock"
suspend="Sleep"
log_out="Logout"
# Variable passed to rofi
options="$power_off\n$reboot\n$lock\n$suspend\n$log_out"

case "$(echo -e "$options" | $rofi_command -dmenu -selected-row 2)" in
    $lock)
        betterlockscreen -l dimblur
        ;;
    $reboot)
        systemctl reboot
        ;;
    $power_off)
        systemctl poweroff
        ;;
    $suspend)
        dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause
        systemctl suspend
        ;;
    $log_out)
        pkill xmonad
        ;;
esac
