#! /bin/sh

sxhkd -c ~/.config/bspwm/sxhkdrc &

##bspc monitor -d TERM MUSIC WEB FILES DEV
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# bspc rule -a URxvt:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset

bspc config focus_follows_pointer true
bspc config border_width         2
bspc config border_radius        20
bspc config window_gap           10
bspc config focused_border_color "#61afef"
bspc config normal_border_color "#000000"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
sh ~/.fehbg &
sh ~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
systemctl --user restart picom &
# picom &
