#!/usr/bin/env sh

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
    ${EWW} daemon
    sleep 1
fi

## Open widgets
run_eww() {
    ${EWW} open-many \
           barCenter \
           user \
           power \
           date \
           control \
           system \
           fetch \
           player \
           home \
           disk \
           downloads \
           pictures \
           documents \
           favourite
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
    touch "$FILE"
    run_eww
else
    ${EWW} close-all
    rm "$FILE"
fi
